//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qwe {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("qwe.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Okay, how are we going to change the text?.
        /// </summary>
        internal static string ChangerT_1 {
            get {
                return ResourceManager.GetString("ChangerT_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Entered error data, return... &lt;==.
        /// </summary>
        internal static string errFinder1 {
            get {
                return ResourceManager.GetString("errFinder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sry, i cant read file....
        /// </summary>
        internal static string errOpened {
            get {
                return ResourceManager.GetString("errOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; copied to this directory:.
        /// </summary>
        internal static string FCopy {
            get {
                return ResourceManager.GetString("FCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Ok, enter the first letter of the local drive (like &quot;C&quot; or &quot;d&quot; or &quot;x&quot;): .
        /// </summary>
        internal static string Finder1 {
            get {
                return ResourceManager.GetString("Finder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Yours disk:.
        /// </summary>
        internal static string Finder1_1 {
            get {
                return ResourceManager.GetString("Finder1.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Enter number what go next:.
        /// </summary>
        internal static string Finder1_2 {
            get {
                return ResourceManager.GetString("Finder1.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Yours folders and files:.
        /// </summary>
        internal static string Finder1_3 {
            get {
                return ResourceManager.GetString("Finder1.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Enter any text to return to the beginning of the path..
        /// </summary>
        internal static string FinderBack {
            get {
                return ResourceManager.GetString("FinderBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &gt; File:.
        /// </summary>
        internal static string FType {
            get {
                return ResourceManager.GetString("FType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count words.
        /// </summary>
        internal static string Info1 {
            get {
                return ResourceManager.GetString("Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Opened file:.
        /// </summary>
        internal static string isOpened {
            get {
                return ResourceManager.GetString("isOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue or exit.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue.
        /// </summary>
        internal static string Next1 {
            get {
                return ResourceManager.GetString("Next1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Ok, the file is written to memory, what should do with it next?.
        /// </summary>
        internal static string Opened {
            get {
                return ResourceManager.GetString("Opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please, select - what do next:.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Find text file, enter the file path manually or open WorkText.txt:.
        /// </summary>
        internal static string Select1 {
            get {
                return ResourceManager.GetString("Select1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  [1] List folder names at specified path.
        /// </summary>
        internal static string Select1_1 {
            get {
                return ResourceManager.GetString("Select1.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deleted.
        /// </summary>
        internal static string Select1_2 {
            get {
                return ResourceManager.GetString("Select1.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  [2] Open WorkText.txt.
        /// </summary>
        internal static string Select1_3 {
            get {
                return ResourceManager.GetString("Select1.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please choose from the suggested options (by number):.
        /// </summary>
        internal static string Select1Err {
            get {
                return ResourceManager.GetString("Select1Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter the path to the file starting from disk (for example D: /work/text.txt):.
        /// </summary>
        internal static string Select2 {
            get {
                return ResourceManager.GetString("Select2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please, enter 1 symbol.
        /// </summary>
        internal static string T1S {
            get {
                return ResourceManager.GetString("T1S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter character to remove it from the file..
        /// </summary>
        internal static string TdelS {
            get {
                return ResourceManager.GetString("TdelS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter word to remove it from the file..
        /// </summary>
        internal static string TdelT {
            get {
                return ResourceManager.GetString("TdelT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected language is english.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Rewrite this document?.
        /// </summary>
        internal static string TextTransfer {
            get {
                return ResourceManager.GetString("TextTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Symbol not found....
        /// </summary>
        internal static string TNF {
            get {
                return ResourceManager.GetString("TNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на String not found....
        /// </summary>
        internal static string TNF1 {
            get {
                return ResourceManager.GetString("TNF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete symbol in file..
        /// </summary>
        internal static string Tselect1_1 {
            get {
                return ResourceManager.GetString("Tselect1.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete word in file..
        /// </summary>
        internal static string Tselect1_2 {
            get {
                return ResourceManager.GetString("Tselect1.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File info + 10th word .
        /// </summary>
        internal static string Tselect1_3 {
            get {
                return ResourceManager.GetString("Tselect1.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The third line with the words in reverse..
        /// </summary>
        internal static string Tselect1_4 {
            get {
                return ResourceManager.GetString("Tselect1.4", resourceCulture);
            }
        }
    }
}
